name: FluxEco
version: '1.0'
main: io.oira.fluxeco.FluxEco
api-version: '1.21'
authors: [ Harfull ]
description: The best free modern economy plugin
website: https://oira.io

folia-supported: true

depend: [ Vault ]
softdepend: [PlaceholderAPI, MiniPlaceholders]

libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:2.2.20"
  - "org.jetbrains.kotlin:kotlin-reflect:2.2.20"
  - "org.jetbrains.kotlinx:kotlinx-serialization-core:1.6.0"
  - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0"
  - "com.zaxxer:HikariCP:7.0.2"
  - "org.jetbrains.exposed:exposed-core:0.61.0"
  - "org.jetbrains.exposed:exposed-dao:0.61.0"
  - "org.jetbrains.exposed:exposed-java-time:0.61.0"
  - "org.jetbrains.exposed:exposed-kotlin-datetime:0.61.0"
  - "org.jetbrains.exposed:exposed-jdbc:0.61.0"
  - "org.xerial:sqlite-jdbc:3.50.3.0"
  - "com.mysql:mysql-connector-j:9.4.0"
  - "com.h2database:h2:2.4.240"
  - "io.github.revxrsal:lamp.common:4.0.0-rc.13"
  - "io.github.revxrsal:lamp.bukkit:4.0.0-rc.13"
  - "io.github.revxrsal:lamp.brigadier:4.0.0-rc.13"
  - "redis.clients:jedis:5.1.0"
  - "org.apache.commons:commons-pool2:2.12.0"
  - "org.slf4j:slf4j-api:2.0.9"
